/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AvatarGroup: typeof import('./src/components/AvatarGroup.vue')['default']
    CalendarDialog: typeof import('./src/components/calendar/CalendarDialog.vue')['default']
    Calendarevents: typeof import('./src/components/calendarevents.vue')['default']
    CalendarEvents: typeof import('./src/components/calendar/CalendarEvents.vue')['default']
    CalendarGrid: typeof import('./src/components/calendar/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/calendar/CalendarHeader.vue')['default']
    CalendarList: typeof import('./src/components/calendar/CalendarList.vue')['default']
    CalendarMain: typeof import('./src/components/calendar/CalendarMain.vue')['default']
    CalendarMainContent: typeof import('./src/components/calendar/CalendarMainContent.vue')['default']
    CalendarSidebar: typeof import('./src/components/calendar/CalendarSidebar.vue')['default']
    CalendarStats: typeof import('./src/components/calendar/CalendarStats.vue')['default']
    CustomCalendar: typeof import('./src/components/calendar/CustomCalendar.vue')['default']
    DatePickerCalendar: typeof import('./src/components/calendar/DatePickerCalendar.vue')['default']
    EnhancedCalendar: typeof import('./src/components/calendar/EnhancedCalendar.vue')['default']
    EventDetailsDialog: typeof import('./src/components/calendar/EventDetailsDialog.vue')['default']
    EventDialog: typeof import('./src/components/calendar/EventDialog.vue')['default']
    EventsList: typeof import('./src/components/calendar/EventsList.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/components/FeaturesSection.vue')['default']
    FuturePlans: typeof import('./src/components/FuturePlans.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    ModernCalendarGrid: typeof import('./src/components/calendar/ModernCalendarGrid.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavbarFloatingControls: typeof import('./src/components/NavbarFloatingControls.vue')['default']
    NotificationContainer: typeof import('./src/components/common/NotificationContainer.vue')['default']
    ProjectDialog: typeof import('./src/components/projects/ProjectDialog.vue')['default']
    ProjectProgress: typeof import('./src/components/ProjectProgress.vue')['default']
    ProjectsHeader: typeof import('./src/components/projects/ProjectsHeader.vue')['default']
    ProjectsList: typeof import('./src/components/projects/ProjectsList.vue')['default']
    ProjectsStats: typeof import('./src/components/projects/ProjectsStats.vue')['default']
    QuickStatCard: typeof import('./src/components/QuickStatCard.vue')['default']
    QuickStatsSection: typeof import('./src/components/QuickStatsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleXCalendar: typeof import('./src/components/calendar/ScheduleXCalendar.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StickyNote: typeof import('./src/components/StickyNote.vue')['default']
    StoreExample: typeof import('./src/components/StoreExample.vue')['default']
    TaskDialog: typeof import('./src/components/tasks/TaskDialog.vue')['default']
    TasksHeader: typeof import('./src/components/tasks/TasksHeader.vue')['default']
    TasksList: typeof import('./src/components/tasks/TasksList.vue')['default']
    TasksStats: typeof import('./src/components/tasks/TasksStats.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
